#!/usr/bin/env bash

set -euo pipefail

PROJECT_DIR=$(cd "$(dirname "$0")/.."; pwd)

# install library dependencies
pip install -r requirements.txt

# execute daft bot
python3 ${PROJECT_DIR}/daft-bot/main.py
